// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-search-reindex-tracker/config"
	"github.com/ONSdigital/dp-search-reindex-tracker/event"
	"sync"
)

// Ensure, that HandlerMock does implement event.Handler.
// If this is not the case, regenerate this file with moq.
var _ event.Handler[event.ReindexRequestedModel] = &HandlerMock{}

// HandlerMock is a mock implementation of event.Handler.
//
// 	func TestSomethingThatUsesHandler(t *testing.T) {
//
// 		// make and configure a mocked event.Handler
// 		mockedHandler := &HandlerMock{
// 			HandleFunc: func(ctx context.Context, cfg *config.Config, reindexRequested *event.ReindexRequested) error {
// 				panic("mock out the Handle method")
// 			},
// 		}
//
// 		// use mockedHandler in code that requires event.Handler
// 		// and then make assertions.
//
// 	}
type HandlerMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(ctx context.Context, cfg *config.Config, reindexRequested *event.ReindexRequestedModel) error

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg *config.Config
			// ReindexRequested is the reindexRequested argument value.
			ReindexRequested *event.ReindexRequestedModel
		}
	}
	lockHandle sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *HandlerMock) Handle(ctx context.Context, cfg *config.Config, reindexRequested *event.ReindexRequestedModel) error {
	if mock.HandleFunc == nil {
		panic("HandlerMock.HandleFunc: method is nil but Handler.Handle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Cfg         *config.Config
		ReindexRequested *event.ReindexRequestedModel
	}{
		Ctx:         ctx,
		Cfg:         cfg,
		ReindexRequested: reindexRequested,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	return mock.HandleFunc(ctx, cfg, reindexRequested)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//     len(mockedHandler.HandleCalls())
func (mock *HandlerMock) HandleCalls() []struct {
	Ctx         context.Context
	Cfg         *config.Config
	ReindexRequested *event.ReindexRequestedModel
} {
	var calls []struct {
		Ctx         context.Context
		Cfg         *config.Config
		ReindexRequested *event.ReindexRequestedModel
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}
